import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const project = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const res = path.join(project, 'app/src/main/res');
const locales = {
  en: 'values', es: 'values-es', fr: 'values-fr', de: 'values-de',
  'pt-BR': 'values-pt-rBR', ja: 'values-ja', 'zh-CN': 'values-zh-rCN',
};
const decode = value => value
  .replace(/\\n/g, '\n').replace(/&amp;/g, '&').replace(/&lt;/g, '<')
  .replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&apos;/g, "'");
function parse(file) {
  const xml = fs.readFileSync(file, 'utf8');
  return Object.fromEntries([...xml.matchAll(/<string\s+[^>]*name="([^"]+)"[^>]*>([\s\S]*?)<\/string>/g)]
    .map(match => [match[1], decode(match[2].trim())]));
}
const catalog = Object.fromEntries(Object.entries(locales).map(([locale, folder]) => [
  locale, parse(path.join(res, folder, 'strings.xml')),
]));
for (const locale of Object.keys(catalog)) catalog[locale].app_name ??= catalog.en.app_name;

const web = {
  en: {
    title:'Borescope Direct — Full App Preview', preview_controls:'Preview state controls', preview:'Preview:', fresh:'New install', one:'One camera', two:'Two cameras', denied:'Permission denied', failed:'Incompatible', expired:'Trial expired', offline:'Play offline', reset:'Reset data', language:'Language', app_preview:'Borescope Direct Android app preview', simulated_live:'Simulated USB endoscope live view', usb_preview:'USB preview', camera_controls:'Camera controls', storage_full:'Browser storage is full; preview state was not saved.', stable_frames:'Waiting for stable video frames…', switched:'Switched to camera %1$d', unlocked:'Unlimited inspections unlocked', video_mark:'▶ Video', share:'Share', close:'Close', deleted:'Capture deleted', capture_copied:'Capture details copied', report_copied:'Compatibility report copied', share_failed:'No app can share this item', preview_reset:'Preview data reset', browser_device:'Browser preview device', simulated:'simulated', delete_dated:'Delete %1$s captured %2$s?', shared_item:'Borescope Direct %1$s — %2$s', count_one:'%1$d capture · %2$s', count_many:'%1$d captures · %2$s', photo_lower:'photo', video_lower:'video', WAITING_FOR_DEVICE:'Waiting for device', CAMERA_PERMISSION_REQUIRED:'Camera permission required', USB_PERMISSION_REQUIRED:'USB permission required', TESTING:'Testing compatibility', LIVE:'Live', PAUSED_FOR_UNLOCK:'Paused for unlock', ERROR:'Error'
  },
  es: {
    title:'Borescope Direct — Vista previa completa', preview_controls:'Controles de estado de la vista previa', preview:'Vista previa:', fresh:'Instalación nueva', one:'Una cámara', two:'Dos cámaras', denied:'Permiso denegado', failed:'No compatible', expired:'Prueba finalizada', offline:'Play sin conexión', reset:'Restablecer datos', language:'Idioma', app_preview:'Vista previa de Borescope Direct para Android', simulated_live:'Vista en directo simulada del endoscopio USB', usb_preview:'Vista previa USB', camera_controls:'Controles de la cámara', storage_full:'El almacenamiento del navegador está lleno; no se guardó el estado de la vista previa.', stable_frames:'Esperando fotogramas de vídeo estables…', switched:'Se cambió a la cámara %1$d', unlocked:'Inspecciones ilimitadas desbloqueadas', video_mark:'▶ Vídeo', share:'Compartir', close:'Cerrar', deleted:'Captura eliminada', capture_copied:'Detalles de la captura copiados', report_copied:'Informe de compatibilidad copiado', share_failed:'Ninguna aplicación puede compartir este elemento', preview_reset:'Datos de la vista previa restablecidos', browser_device:'Dispositivo de vista previa del navegador', simulated:'simulada', delete_dated:'¿Eliminar la %1$s capturada el %2$s?', shared_item:'%1$s de Borescope Direct — %2$s', count_one:'%1$d captura · %2$s', count_many:'%1$d capturas · %2$s', photo_lower:'foto', video_lower:'vídeo', WAITING_FOR_DEVICE:'Esperando dispositivo', CAMERA_PERMISSION_REQUIRED:'Se necesita permiso de cámara', USB_PERMISSION_REQUIRED:'Se necesita permiso USB', TESTING:'Probando compatibilidad', LIVE:'En directo', PAUSED_FOR_UNLOCK:'En pausa para desbloquear', ERROR:'Error'
  },
  fr: {
    title:'Borescope Direct — Aperçu complet', preview_controls:'Commandes d’état de l’aperçu', preview:'Aperçu :', fresh:'Nouvelle installation', one:'Une caméra', two:'Deux caméras', denied:'Autorisation refusée', failed:'Incompatible', expired:'Essai terminé', offline:'Play hors connexion', reset:'Réinitialiser les données', language:'Langue', app_preview:'Aperçu Android de Borescope Direct', simulated_live:'Vue en direct simulée de l’endoscope USB', usb_preview:'Aperçu USB', camera_controls:'Commandes de la caméra', storage_full:'Le stockage du navigateur est saturé ; l’état de l’aperçu n’a pas été enregistré.', stable_frames:'En attente d’images vidéo stables…', switched:'Caméra %1$d sélectionnée', unlocked:'Inspections illimitées déverrouillées', video_mark:'▶ Vidéo', share:'Partager', close:'Fermer', deleted:'Capture supprimée', capture_copied:'Détails de la capture copiés', report_copied:'Rapport de compatibilité copié', share_failed:'Aucune application ne peut partager cet élément', preview_reset:'Données de l’aperçu réinitialisées', browser_device:'Appareil de prévisualisation du navigateur', simulated:'simulée', delete_dated:'Supprimer la %1$s du %2$s ?', shared_item:'%1$s Borescope Direct — %2$s', count_one:'%1$d capture · %2$s', count_many:'%1$d captures · %2$s', photo_lower:'photo', video_lower:'vidéo', WAITING_FOR_DEVICE:'En attente d’un appareil', CAMERA_PERMISSION_REQUIRED:'Autorisation Appareil photo requise', USB_PERMISSION_REQUIRED:'Autorisation USB requise', TESTING:'Test de compatibilité', LIVE:'Direct', PAUSED_FOR_UNLOCK:'En pause avant déverrouillage', ERROR:'Erreur'
  },
  de: {
    title:'Borescope Direct – Vollständige App-Vorschau', preview_controls:'Statussteuerung der Vorschau', preview:'Vorschau:', fresh:'Neuinstallation', one:'Eine Kamera', two:'Zwei Kameras', denied:'Berechtigung verweigert', failed:'Nicht kompatibel', expired:'Test abgelaufen', offline:'Play offline', reset:'Daten zurücksetzen', language:'Sprache', app_preview:'Android-App-Vorschau von Borescope Direct', simulated_live:'Simulierte Liveansicht des USB-Endoskops', usb_preview:'USB-Vorschau', camera_controls:'Kamerasteuerung', storage_full:'Der Browserspeicher ist voll; der Vorschaustatus wurde nicht gespeichert.', stable_frames:'Warten auf stabile Videobilder…', switched:'Zu Kamera %1$d gewechselt', unlocked:'Unbegrenzte Inspektionen freigeschaltet', video_mark:'▶ Video', share:'Teilen', close:'Schließen', deleted:'Aufnahme gelöscht', capture_copied:'Aufnahmedetails kopiert', report_copied:'Kompatibilitätsbericht kopiert', share_failed:'Keine App kann dieses Element teilen', preview_reset:'Vorschaudaten zurückgesetzt', browser_device:'Browser-Vorschaugerät', simulated:'simuliert', delete_dated:'Am %2$s aufgenommene %1$s löschen?', shared_item:'Borescope Direct: %1$s – %2$s', count_one:'%1$d Aufnahme · %2$s', count_many:'%1$d Aufnahmen · %2$s', photo_lower:'Foto', video_lower:'Video', WAITING_FOR_DEVICE:'Warten auf Gerät', CAMERA_PERMISSION_REQUIRED:'Kameraberechtigung erforderlich', USB_PERMISSION_REQUIRED:'USB-Berechtigung erforderlich', TESTING:'Kompatibilität wird getestet', LIVE:'Live', PAUSED_FOR_UNLOCK:'Für Freischaltung pausiert', ERROR:'Fehler'
  },
  'pt-BR': {
    title:'Borescope Direct — Prévia completa do app', preview_controls:'Controles de estado da prévia', preview:'Prévia:', fresh:'Nova instalação', one:'Uma câmera', two:'Duas câmeras', denied:'Permissão negada', failed:'Incompatível', expired:'Teste encerrado', offline:'Play off-line', reset:'Redefinir dados', language:'Idioma', app_preview:'Prévia do Borescope Direct para Android', simulated_live:'Imagem ao vivo simulada do endoscópio USB', usb_preview:'Prévia USB', camera_controls:'Controles da câmera', storage_full:'O armazenamento do navegador está cheio; o estado da prévia não foi salvo.', stable_frames:'Aguardando quadros de vídeo estáveis…', switched:'Câmera %1$d selecionada', unlocked:'Inspeções ilimitadas desbloqueadas', video_mark:'▶ Vídeo', share:'Compartilhar', close:'Fechar', deleted:'Captura excluída', capture_copied:'Detalhes da captura copiados', report_copied:'Relatório de compatibilidade copiado', share_failed:'Nenhum app pode compartilhar este item', preview_reset:'Dados da prévia redefinidos', browser_device:'Dispositivo de prévia do navegador', simulated:'simulada', delete_dated:'Excluir a %1$s capturada em %2$s?', shared_item:'%1$s do Borescope Direct — %2$s', count_one:'%1$d captura · %2$s', count_many:'%1$d capturas · %2$s', photo_lower:'foto', video_lower:'vídeo', WAITING_FOR_DEVICE:'Aguardando dispositivo', CAMERA_PERMISSION_REQUIRED:'Permissão da câmera necessária', USB_PERMISSION_REQUIRED:'Permissão USB necessária', TESTING:'Testando compatibilidade', LIVE:'Ao vivo', PAUSED_FOR_UNLOCK:'Pausado para desbloqueio', ERROR:'Erro'
  },
  ja: {
    title:'Borescope Direct — アプリ全体プレビュー', preview_controls:'プレビュー状態の操作', preview:'プレビュー：', fresh:'新規インストール', one:'カメラ1台', two:'カメラ2台', denied:'権限を拒否', failed:'非対応', expired:'試用終了', offline:'Playオフライン', reset:'データをリセット', language:'言語', app_preview:'Borescope Direct Androidアプリのプレビュー', simulated_live:'USB内視鏡のライブ映像シミュレーション', usb_preview:'USBプレビュー', camera_controls:'カメラ操作', storage_full:'ブラウザの保存容量が不足しているため、プレビューの状態を保存できませんでした。', stable_frames:'安定した映像フレームを待っています…', switched:'カメラ%1$dに切り替えました', unlocked:'回数制限なしの点検を利用できます', video_mark:'▶ 動画', share:'共有', close:'閉じる', deleted:'撮影データを削除しました', capture_copied:'撮影データの詳細をコピーしました', report_copied:'互換性レポートをコピーしました', share_failed:'この項目を共有できるアプリがありません', preview_reset:'プレビューデータをリセットしました', browser_device:'ブラウザのプレビュー端末', simulated:'シミュレーション', delete_dated:'%2$sに撮影した%1$sを削除しますか？', shared_item:'Borescope Directの%1$s — %2$s', count_one:'%1$d件・%2$s', count_many:'%1$d件・%2$s', photo_lower:'写真', video_lower:'動画', WAITING_FOR_DEVICE:'デバイスを待機中', CAMERA_PERMISSION_REQUIRED:'カメラ権限が必要', USB_PERMISSION_REQUIRED:'USB権限が必要', TESTING:'互換性をテスト中', LIVE:'ライブ', PAUSED_FOR_UNLOCK:'購入待ちで一時停止', ERROR:'エラー'
  },
  'zh-CN': {
    title:'Borescope Direct — 完整应用预览', preview_controls:'预览状态控制', preview:'预览：', fresh:'全新安装', one:'一台相机', two:'两台相机', denied:'权限被拒绝', failed:'不兼容', expired:'试用已结束', offline:'Play离线', reset:'重置数据', language:'语言', app_preview:'Borescope Direct Android应用预览', simulated_live:'模拟USB内窥镜实时画面', usb_preview:'USB预览', camera_controls:'相机控制', storage_full:'浏览器存储空间已满，未保存预览状态。', stable_frames:'正在等待稳定的视频画面…', switched:'已切换到相机%1$d', unlocked:'已解锁无限次检查', video_mark:'▶ 视频', share:'分享', close:'关闭', deleted:'文件已删除', capture_copied:'文件详情已复制', report_copied:'兼容性报告已复制', share_failed:'没有可分享此项目的应用', preview_reset:'预览数据已重置', browser_device:'浏览器预览设备', simulated:'模拟', delete_dated:'要删除%2$s拍摄的%1$s吗？', shared_item:'Borescope Direct %1$s — %2$s', count_one:'%1$d项 · %2$s', count_many:'%1$d项 · %2$s', photo_lower:'照片', video_lower:'视频', WAITING_FOR_DEVICE:'正在等待设备', CAMERA_PERMISSION_REQUIRED:'需要相机权限', USB_PERMISSION_REQUIRED:'需要USB权限', TESTING:'正在测试兼容性', LIVE:'实时画面', PAUSED_FOR_UNLOCK:'已暂停，等待解锁', ERROR:'错误'
  },
};

const runtime = String.raw`
(()=>{
  'use strict';
  const catalog=__CATALOG__, web=__WEB__, supported=['en','es','fr','de','pt-BR','ja','zh-CN'];
  const normalize=value=>{const v=String(value||'');if(/^pt\b/i.test(v))return'pt-BR';if(/^zh\b/i.test(v))return'zh-CN';const short=v.slice(0,2).toLowerCase();return supported.includes(short)?short:'en';};
  let locale=normalize(localStorage.getItem('borescope-direct-locale')||navigator.language);
  const pairs=(from='en',to=locale)=>[...Object.keys(catalog.en).map(k=>[catalog[from][k],catalog[to][k]]),...Object.keys(web.en).map(k=>[web[from][k],web[to][k]])];
  const exact=(from,to)=>new Map(pairs(from,to).filter(([a])=>!/%\d+\$[sd]/.test(a)));
  const esc=value=>value.replace(/[.*+?^{}()|[\]\\$]/g,'\\$&');
  function template(value,source,target,from,to){let pattern='^',cursor=0,indexes=[];for(const m of source.matchAll(/%(\d+)\$[sd]/g)){pattern+=esc(source.slice(cursor,m.index))+'(.+?)';indexes.push(Number(m[1]));cursor=m.index+m[0].length;}pattern+=esc(source.slice(cursor))+'$';const hit=value.match(new RegExp(pattern,'u'));if(!hit)return null;const args={};indexes.forEach((index,i)=>args[index]=convertOne(hit[i+1],from,to));return target.replace(/%(\d+)\$[sd]/g,(_,index)=>args[Number(index)]??'');}
  function convertOne(value,from='en',to=locale){if(from===to)return value;const direct=exact(from,to).get(value);if(direct!==undefined)return direct;for(const [source,target] of pairs(from,to)){if(!/%\d+\$[sd]/.test(source))continue;const result=template(value,source,target,from,to);if(result!==null)return result;}return value;}
  function convert(value,from='en',to=locale){const raw=String(value??''),whole=convertOne(raw,from,to);if(whole!==raw)return whole;return raw.split(/(\n)/).map(part=>part==='\n'?part:convertOne(part,from,to)).join('');}
  const translate=value=>convert(value,'en',locale);
  function translateTree(root,from='en',to=locale){if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){if(node.parentElement?.closest('#languageSelect,script,style'))continue;const before=node.nodeValue,trim=before.trim();if(!trim)continue;const after=convert(trim,from,to);if(after!==trim)node.nodeValue=before.replace(trim,after);}for(const el of [root,...root.querySelectorAll?.('[aria-label],[title]')||[]]){for(const attr of ['aria-label','title'])if(el.getAttribute?.(attr)){el.setAttribute(attr,convert(el.getAttribute(attr),from,to));}}}
  const nativeConfirm=window.confirm.bind(window);window.confirm=message=>nativeConfirm(translate(message));
  const api={get locale(){return locale;},translate};globalThis.bdL10n=api;
  document.documentElement.lang=locale;document.title=translate(web.en.title);
  addEventListener('DOMContentLoaded',()=>{const select=document.getElementById('languageSelect');if(select){select.value=locale;select.addEventListener('change',()=>{const previous=locale;translateTree(document.body,previous,'en');locale=normalize(select.value);localStorage.setItem('borescope-direct-locale',locale);document.documentElement.lang=locale;document.title=translate(web.en.title);translateTree(document.body);dispatchEvent(new CustomEvent('borescope-locale-change'));});}translateTree(document.body);new MutationObserver(records=>{for(const record of records){if(record.type==='characterData')translateTree(record.target.parentElement);else for(const node of record.addedNodes)if(node.nodeType===Node.ELEMENT_NODE)translateTree(node);else if(node.nodeType===Node.TEXT_NODE)translateTree(node.parentElement);}}).observe(document.body,{subtree:true,childList:true,characterData:true});});
})();`;
const output = runtime
  .replace('__CATALOG__', JSON.stringify(catalog))
  .replace('__WEB__', JSON.stringify(web));
fs.writeFileSync(path.join(project, 'html-preview/l10n.generated.js'), output + '\n');
console.log(`Generated web localization: ${Object.keys(catalog.en).length} shared strings + ${Object.keys(web.en).length} web strings × ${Object.keys(locales).length} locales`);

export { catalog, web };
